### ISSUE TITLE
在使用redis情况下抛出异常无法加载到jedis的类，加入后还是抛出异常

### ISSUE THREAD

**Issue by yezhu20** [teaey/spring-boot-starter-dubbo#309]
问题如上，是否现在版本不知道redis

**Comment by 15174834** [comment]
问题描述不是很清楚啊

**Comment by yezhu20** [comment]
src/main/resources/application.properties
spring.dubbo.registry.address=redis://localhost:6379
用redis注册，则出现以下异常
`Caused by: java.lang.ClassNotFoundException: redis.clients.jedis.Jedis
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 30 more`
