### ISSUE TITLE
您好，我用您这个在Controller层消费dubbo服务的时候，实例注入的都是null

### ISSUE THREAD

**Issue by chenkesheng** [teaey/spring-boot-starter-dubbo#310]
2017-08-28 11:23:39.474 [http-nio-8020-exec-1] INFO  org.springframework.web.servlet.DispatcherServlet - FrameworkServlet 'dispatcherServlet': initialization started
信息: Initializing Spring FrameworkServlet 'dispatcherServlet'
2017-08-28 11:23:39.478 [http-nio-8020-exec-1] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'org.springframework.web.servlet.i18n.AcceptHeaderLocaleResolver' of type [org.springframework.web.servlet.i18n.AcceptHeaderLocaleResolver] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-08-28 11:23:39.483 [http-nio-8020-exec-1] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'org.springframework.web.servlet.theme.FixedThemeResolver' of type [org.springframework.web.servlet.theme.FixedThemeResolver] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-08-28 11:23:39.488 [http-nio-8020-exec-1] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'org.springframework.web.servlet.view.DefaultRequestToViewNameTranslator' of type [org.springframework.web.servlet.view.DefaultRequestToViewNameTranslator] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-08-28 11:23:39.495 [http-nio-8020-exec-1] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'org.springframework.web.servlet.support.SessionFlashMapManager' of type [org.springframework.web.servlet.support.SessionFlashMapManager] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-08-28 11:23:39.496 [http-nio-8020-exec-1] INFO  org.springframework.web.servlet.DispatcherServlet - FrameworkServlet 'dispatcherServlet': initialization completed in 22 ms
八月 28, 2017 11:23:48 上午 org.apache.catalina.core.StandardWrapperValve invoke
严重: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause
java.lang.NullPointerException
	at com.cksmaster.user.controller.UserServiceController.find(UserServiceController.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)

**Comment by 15174834** [comment]
1.检查scan的包路径是否扫描到使用@reference的类包路径
2.把register的check，provider的check，refrence的check，都设为false

**Comment by shenzhuan** [comment]
http://git.oschina.net/catshen/zscat_sw  看看这个整合吧
